sudo: required

dist: bionic

services:
  - docker

# arch:
  # repos:
    # - archlinuxfr=http://repo.archlinux.fr/$arch
  # packages:
    # - fuse2
    # - wget
    # - gcc
    # - make
    # - cmake
    # - patchelf
    # - lib32-gcc-libs
    # - ncurses
    # - ncurses5-compat-libs
  # script:
    # - "make"
    #

before_install:
  - sudo add-apt-repository ppa:longsleep/golang-backports -y
  - sudo apt update -q
  - sudo apt install -y build-essential
  - sudo apt install -y make
  - sudo apt install -y cmake
  - sudo apt install -y patchelf
  - sudo apt install -y gcc-multilib
  - sudo apt install -y libncurses-dev
  - sudo apt install -y zlib1g-dev
  - sudo apt install -y golang-go

script:
  - "make"

after_success:
  - ls -lh space-vim-bundle.tar.gz
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh space-vim-bundle.tar.gz

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
