sudo: required

services:
- docker

arch:
  repos:
  - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
  - wget
  - gcc
  - make
  - cmake
  - patchelf
  - lib32-gcc-libs
  - ncurses
  - ncurses5-compat-libs
  script:
  - "make"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
